apiVersion: batch/v1
kind: CronJob
metadata:
  name: echoserver
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: echoserver
        spec:
          restartPolicy: Never
          containers:
            - image: busybox:1.28
              name: echoserver
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
