apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-fixture1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: gcr.io/google_containers/echoserver:1.8
          name: echoserver-fixture1
          ports:
            - containerPort: 8080
