# This rule is not used by the project kubebuilder-updates itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the webapp.int128.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argocd-commenter
    app.kubernetes.io/managed-by: kustomize
  name: applicationhealth-editor-role
rules:
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - applicationhealths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - applicationhealths/status
  verbs:
  - get
