# permissions for end users to edit githubcomments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubcomment-editor-role
rules:
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - githubcomments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - githubcomments/status
  verbs:
  - get
