# permissions for end users to view githubcomments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubcomment-viewer-role
rules:
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - githubcomments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argocdcommenter.int128.github.io
  resources:
  - githubcomments/status
  verbs:
  - get
