resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3f882eb7179bc20416ba3e1f0d0c170da482e1974fdc2575a718946d4eac8822
  name: controller
  newName: ghcr.io/int128/argocd-commenter
