resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4fe675fa985477042c6dd96f1626d9fe4491b94eb11422302a4d0c7595ae12a3
  name: controller
  newName: ghcr.io/int128/argocd-commenter
