resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:fc4ae8b74fbc3011c4e8430e5df3aa0fb826e37bb7fcb1f065094f2e77f4ebdc
  name: controller
  newName: ghcr.io/int128/argocd-commenter
