resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:ed91593a13d2b0379f1f37196119555c281ec09b3484c56dc6c73cac9cdceb15
  name: controller
  newName: ghcr.io/int128/argocd-commenter
