resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4b18632ab8467fecf27d2159afd14dc444370c7af8a72c021a34dbb23e50152f
  name: controller
  newName: ghcr.io/int128/argocd-commenter
