resources:
- ../../config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d9fddb182219d870deb125e85f576ec1c350cbac39d04f51c902052f389494bf
  name: controller
  newName: ghcr.io/int128/argocd-commenter
