apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-commenter-controller-manager
  namespace: argocd-commenter-system
spec:
  template:
    spec:
      containers:
        - name: manager
          # https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster
          imagePullPolicy: Never
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-commenter-secret
                  key: GITHUB_TOKEN
