apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/int128/argocd-commenter-e2e-test
    targetRevision: FIXTURE_BASE_BRANCH
    path: app2
  destination:
    server: https://kubernetes.default.svc
    namespace: test2-fixture
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1  # reduce test time
