apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/int128/argocd-commenter-e2e-test
    targetRevision: FIXTURE_BRANCH/test3/main
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: test3
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    # reduce time of test
    retry:
      limit: 1
      backoff:
        duration: 1s
        factor: 1
        maxDuration: 1s
