apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app3
  namespace: argocd
  labels:
    int128.github.io/e2e-test: fixture
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
  sources:
    - repoURL: https://github.com/int128/argocd-commenter-e2e-test
      targetRevision: FIXTURE_BASE_BRANCH
      path: app3
  destination:
    server: https://kubernetes.default.svc
    namespace: test3-fixture
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1  # reduce test time
