apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fixtures
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/int128/argocd-commenter-e2e-test
        revision: FIXTURE_BASE_BRANCH
        files:
          - path: "*"
  template:
    metadata:
      name: "{{ .path.basename }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/int128/argocd-commenter-e2e-test
        targetRevision: FIXTURE_BASE_BRANCH
        path: "{{ .path.basename }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
        retry:
          limit: 1 # To reduce time
