apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: e2e-test
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/int128/argocd-commenter-e2e-test
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: '*'
