apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test2-fixture
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/int128/argocd-commenter
    targetRevision: FIXTURE_BRANCH-test2-main
    path: e2e_test/test2-fixture
  destination:
    server: https://kubernetes.default.svc
    namespace: test2-fixture
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 1  # reduce test time
