apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test1-fixture
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/int128/argocd-commenter
    targetRevision: FIXTURE_BRANCH-test1-main
    path: e2e_test/test1-fixture
  destination:
    server: https://kubernetes.default.svc
    namespace: test1-fixture
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
