name: delete-outdated-deployments

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/delete-outdated-deployments.yaml

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/delete-deployments-action@36ed8904b8f81416210b43b973d1cb95914f0c43 # v1.68.0
