name: delete-outdated-deployments

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/delete-outdated-deployments.yaml

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/delete-deployments-action@ea5f414eb0ca464aabc68c86aa16e1877e2d9843 # v1.57.0
