name: delete-outdated-deployments

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - .github/workflows/delete-outdated-deployments.yaml

jobs:
  delete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/delete-deployments-action@6ebe74059d847e6e4d58271324c10911a0d72f62 # v1.50.0
