name: deployment-status

on:
  deployment_status:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            core.info(JSON.stringify(context, undefined, 2))

      - if: github.event.deployment_status.state == 'failure'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `:x: Failed to deploy ${context.payload.deployment_status.environment}`
            })
