name: deployment-status

on:
  deployment_status:

jobs:
  notify:
    name: notify / ${{ github.event.deployment.environment }} / ${{ github.event.deployment_status.state }}
    if: |
      github.event.deployment_status.state == 'success' ||
      github.event.deployment_status.state == 'failure'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context, undefined, 2))
      - uses: int128/aggregate-deployments-action@v0
        id: deployments
      - if: steps.deployments.outputs.completed
        uses: int128/comment-action@v1
        with:
          post: |
            ## Deployed applications
            ${{ steps.deployments.outputs.summary }}
