name: deployment-status

on:
  deployment_status:

jobs:
  notify:
    name: notify / ${{ github.event.deployment.environment }} / ${{ github.event.deployment_status.state }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            core.info(JSON.stringify(context, undefined, 2))
