name: go

on:
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
      - Makefile
  push:
    branches:
      - main
    paths:
      - .github/workflows/go.yaml
      - go.*
      - '**/*.go'
      - Makefile

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make test
      - run: make lint

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: bash hack/fix_go_mod_replace.sh
      - run: make fmt
      - run: make generate manifests
      - uses: int128/update-generated-files-action@9662c04ea188ea4238f93acda9e35e2edc49a385 # v2.82.0
