name: manifest

on:
  pull_request:
    paths:
      - config/**
      - e2e_test/**
      - .github/workflows/manifest.yaml

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ github.head_ref }}
          path: head
      - uses: int128/kustomize-action@1cc093a17cff63e6215866362414fde7cc9c7e8f # v1.186.0
        id: kustomize-head
        with:
          base-directory: head
          write-individual-files: true
          kustomization: |
            config/default/kustomization.yaml
            e2e_test/**/kustomization.yaml

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ github.base_ref }}
          path: base
      - uses: int128/kustomize-action@1cc093a17cff63e6215866362414fde7cc9c7e8f # v1.186.0
        id: kustomize-base
        with:
          base-directory: base
          write-individual-files: true
          ignore-kustomize-error: true
          kustomization: |
            config/default/kustomization.yaml
            e2e_test/**/kustomization.yaml

      - uses: int128/diff-action@4ea4f95e4684b2c719b963eefd7ff4b76d06ff8b # v2.36.0
        id: diff
        with:
          base: ${{ steps.kustomize-base.outputs.directory }}
          head: ${{ steps.kustomize-head.outputs.directory }}
      - uses: int128/comment-action@012d07c1feb8a1e85933b77c7f72a73d82026805 # v1.73.0
        with:
          update-if-exists: replace
          post: |
            ## ${{ github.workflow }} / ${{ github.job }}
            ${{ steps.diff.outputs.comment-body || 'No diff' }}
