name: release

on:
  push:
    tags:
      - v*
  pull_request:
    paths:
      - config/**
      - .github/workflows/release.yaml

jobs:
  manifest:
    uses: int128/kubebuilder-workflows/.github/workflows/release.yaml@e6411bdb370db1900260cf86e13c20980c3eaa82 # v1
    permissions:
      contents: write
