name: renovate-config

on:
  pull_request:
    paths:
      - .github/workflows/renovate-config.yaml
      - .github/renovate.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config.yaml
      - .github/renovate.*

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@90f976f0de61b5f14b7835f52175f32b2eb4d353 # main
