name: renovate-config

on:
  pull_request:
    paths:
      - .github/workflows/renovate-config.yaml
      - .github/renovate.*
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate-config.yaml
      - .github/renovate.*

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@main
